general =
{
    name = "Bluetooth Speaker";
    udp_port_base = 6011;
    udp_port_range = 10;

    output_backend = "alsa";
    playback_mode = "stereo";
    interpolation = "soxr";

    audio_backend_latency_offset_in_seconds = 0.15;
};

sessioncontrol =
{
    active_state_timeout = 0;
    allow_session_interruption = "yes";
    session_timeout = 0;
};
